#ifndef OPS_UTILS_INC_OP_HOST_DATA_COPY_TRANSPOSE_TILING_H
#define OPS_UTILS_INC_OP_HOST_DATA_COPY_TRANSPOSE_TILING_H

#include "../tiling/data_copy_transpose_tiling.h"

#endif // OPS_UTILS_INC_OP_HOST_DATA_COPY_TRANSPOSE_TILING_H
