#ifndef OPS_UTILS_INC_OP_HOST_TILING_TEMPLATES_REGISTRY_H
#define OPS_UTILS_INC_OP_HOST_TILING_TEMPLATES_REGISTRY_H

#include "../tiling/tiling_templates_registry.h"

#endif // OPS_UTILS_INC_OP_HOST_TILING_TEMPLATES_REGISTRY_H
